Bump to 1.32.5 (updated node_preamble.dart)
sass/dart-sass pull request #1207
Opened 2021-01-16 00:09 UTC by Mstrodl

Similar to #1028, pulls mbullington/node_preamble.dart#21

2021-01-16 00:30 UTC, nex3 requested changes

2021-01-16 00:30 UTC, nex3 commented on CHANGELOG.md
> +* Use an updated version of `node_preamble` when compiling to JS.
Generally, we try to keep changelog entries focused on the user's perspective. What does the latest version of `node_preamble` allow/fix that older versions did not?

2021-01-17 02:14 UTC, Mstrodl commented
@nex3 I've updated the changelog as requested

2021-01-20 02:19 UTC, merged

2021-01-21 17:24 UTC, Mstrodl commented
@stof See the old PR, I was told not to change it because it still fits within the semver.

2021-01-21 17:25 UTC, Mstrodl commented
Ironically however this doesn't even fix my issue because node_preamble.dart didn't actually have it's version number changed... Oops.

2021-01-21 17:31 UTC, stof commented
but if the fix requires the new version of the library, bumping the min version of the constraint would make sense to be sure that `pub` cannot select the older buggy version. Otherwise, the fix is not enforced.

2021-01-21 17:40 UTC, Mstrodl commented
@stof I agree with what you're saying, I'm just explaining why I didn't bump it (I did try the first time, see #1012 .)

2021-01-21 17:44 UTC, stof commented
well, then the issue is not actually fixed, because the fix you want to bring in is not yet released on https://pub.dev/packages/node_preamble

2021-01-22 01:55 UTC, Mstrodl commented
@stof Correct! I have opened a pull request on the node_preamble repository because I forgot: mbullington/node_preamble.dart#23