Fix pre-existing HintCode.UNNECESSARY_TYPE_CHECK_TRUE
sass/dart-sass pull request #1457
Opened 2021-09-01 19:26 UTC by scheglov

This prepares for landing https://dart-review.googlesource.com/c/sdk/+/190360 into the analyzer.

2021-09-02 00:46 UTC, nex3 requested changes
This code is actually more complicated than it looks. Although the type check in question isn't necessary in `async_evaluate.dart`, that code is compiled to the synchronous `evaluate.dart` and transformed into a `callable is Callable` check which *is* relevant. Can you just add an ignore for the hint instead?

2021-09-02 02:24 UTC, scheglov commented
Done.

2021-09-02 19:45 UTC, nex3 approved these changes

2021-09-03 20:06 UTC, scheglov commented
Could you merge these changes? It seems that I don't have corresponding permissions.

2021-09-07 19:21 UTC, merged