Validate ImporterResult 'contents' and improve ArgumentError output
sass/dart-sass pull request #1816
Opened 2022-10-28 00:46 UTC by Goodwine

Example output:
```
/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:1302
      wrapper = new Error();
                ^
sass.Exception [Error]: Invalid argument (contents): must be a string but was: Buffer.: Instance of 'NativeUint8List'
  ╷
1 │ @import './foo.wxss';
  │         ^^^^^^^^^^^^
  ╵
  - 1:9  root stylesheet
    at Object.wrapException (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:1302:17)
    at Object.throwExpression (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:1316:15)
    at Object.ImporterResult$ (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:22031:11)
    at NodeToDartImporter.load$1 (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:101226:16)
    at ImportCache_importCanonical_closure0.call$0 (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:88832:33)
    at JsLinkedHashMap.putIfAbsent$2 (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:28525:24)
    at ImportCache0.importCanonical$4$originalUrl$quiet (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:88770:46)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$4$baseUrl$forImport (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:83622:38)
    at _EvaluateVisitor1._evaluate0$_loadStylesheet$3$forImport (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:83674:19)
    at _EvaluateVisitor__visitDynamicImport_closure1.call$0 (/home/goodwine/repos/dart-sass/build/npm/sass.dart.js:85557:21)
```

2022-10-31 20:43 UTC, nex3 requested changes
Can you add a test for this to `sass-spec` as well?

2022-10-31 20:43 UTC, nex3 commented on CHANGELOG.md
> +* Importer result argument errors are now rendered correctly.
Nit: We usually include a blank line between bullet points to help with plain-text readability.

2022-11-01 01:33 UTC, Goodwine commented
> Can you add a test for this to sass-spec as well?

I wasn't sure where were the tests actually, but I found them now 🙂

Added tests and updated to also handle legacy importers which I realized just now via testing that it wasn't handled (yay tests)

2022-11-03 23:48 UTC, nex3 approved these changes

2022-11-03 23:50 UTC, merged