Deprecate user-defined functions with math function names
sass/dart-sass pull request #2068
Opened 2023-08-17 22:52 UTC by nex3

See #1934
See sass/sass#3504
See sass/sass-spec#1932

2023-08-18 00:01 UTC, Goodwine approved these changes

2023-08-18 00:04 UTC, Goodwine commented on lib/src/parse/stylesheet.dart
> +          'More info: https:/sass-lang.com/d/math-fn-name',
The only nit is that this page is not live yet, but I understand it should go live soon

2023-08-18 01:56 UTC, Goodwine requested changes

2023-08-18 01:56 UTC, Goodwine commented on lib/src/parse/stylesheet.dart
> +          'More info: https:/sass-lang.com/d/math-fn-name',
Oh actually on second look, there is a missing `/`
```suggestion
          'More info: https://sass-lang.com/d/math-fn-name',
```

2023-08-29 21:20 UTC, nex3 commented
Closing this out in favor of the approach described in https://github.com/sass/sass/pull/3661

2023-08-29 21:20 UTC, closed without merging