Implement support for the relative color syntax of CSS Color 5
sass/dart-sass pull request #2098
Opened 2023-09-27 13:21 UTC by stof

Implements the change for https://github.com/sass/sass/pull/3676

https://github.com/sass/sass-spec/pull/1940

2023-09-27 23:51 UTC, nex3 requested changes

2023-09-27 23:51 UTC, nex3 commented on lib/src/functions/color.dart
> +  }
```suggestion
  if (list case [SassString(:var text, hasQuotes: false), _, ...]
      when equalsIgnoreCase(text, "from")) {
    return _functionString(name, [originalChannels]);
  }
```

2023-09-28 06:15 UTC, stof commented on lib/src/functions/color.dart
> +  }
updated

2023-09-28 22:45 UTC, nex3 approved these changes

2023-09-28 22:47 UTC, merged

2023-09-28 22:47 UTC, nex3 commented
Thanks!