add --random-seed option
sass/dart-sass pull request #2359
Opened 2024-09-20 16:57 UTC by Joshix-1

2024-09-20 20:55 UTC, nex3 requested changes
I think this is a good concept, but it doesn't take into account running the compiler from the Dart or JS APIs or through the embedded protocol. This will require a proper [proposal](https://github.com/sass/sass/blob/main/CONTRIBUTING.md).

2024-09-20 20:55 UTC, nex3 commented on lib/src/executable/compile_stylesheet.dart
> +import '../util/random.dart' show setRandomSeed;
Style nit: typically in Dart you don't explicitly `show` the names you use.

2024-09-20 21:13 UTC, Joshix-1 commented
> This will require a proper [proposal](https://github.com/sass/sass/blob/main/CONTRIBUTING.md).
Why? I don't see this as a new sass feature, as it doesn't really introduce anything new. The "random" algorithm seems to be an implementation detail. This only adds a flag to configure the random algorithm a bit.

2024-09-20 22:37 UTC, nex3 commented
Anything that's configurable via the CLI also needs to be configurable through the API, and any changes to the JS API need a language proposal because it's part of the Sass specification.

2024-10-14 20:42 UTC, nex3 commented
Since it's been three weeks, I'm going to close this out. We may end up resurrecting it if/when we go through the full proposal process for adding a new configuration option.

2024-10-14 20:42 UTC, closed without merging