Update LMS matrices
sass/dart-sass pull request #2374
Opened 2024-10-02 21:04 UTC by nex3

This recomputes all existing LMS-related matrices based on the
improved XYZD65/LMS matrices in
w3c/csswg-drafts#6642#issuecomment-1490068959.

See sass/sass-spec#2026

2024-10-02 22:01 UTC, nex3 commented
Probably shouldn't land this until https://github.com/w3c/csswg-drafts/issues/6642#issuecomment-2389764762 is resolved.

2024-10-07 18:52 UTC, ntkme requested changes

2024-10-07 18:52 UTC, ntkme commented on lib/src/value/color/conversions.dart
>  /// Note that this can't be directly multiplied with [lmsToD65Xyz]; see Color
```suggestion
/// Note that this can't be directly multiplied with [lmsToXyzD65]; see Color
```

2024-10-07 18:52 UTC, ntkme commented on lib/src/value/color/conversions.dart
>  /// Note that this can't be directly multiplied with [d65XyzToLms]; see Color
```suggestion
/// Note that this can't be directly multiplied with [xyzD65ToLms]; see Color
```

2024-10-10 16:25 UTC, jathak approved these changes

2024-10-10 23:57 UTC, merged